package com.rustyrazorblade.easydblab.services

import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

/**
 * Tests for [DefaultKitCommandScanner]. Verifies core scanner behaviour: unknown kit names
 * return empty, and results are cached across calls.
 *
 * Note: the `presto sql` and `clickhouse sql` commands are now generated by the capabilities
 * model and are NOT annotated with @KitCommand. The scanner is only used for one-off
 * Kotlin commands that don't fit a standard capability type.
 */
class KitCommandScannerTest {
    private val scanner = DefaultKitCommandScanner()

    @Test
    fun `forKit returns empty list for unknown kit`() {
        val commands = scanner.forKit("nonexistent-kit")
        assertThat(commands).isEmpty()
    }

    @Test
    fun `result is cached across calls`() {
        val first = scanner.findAll()
        val second = scanner.findAll()
        assertThat(first).isSameAs(second)
    }
}
