{
 "title": "Cassandra Cluster Condensed",
 "description": "Single pane of glass for most important Cassandra metrics",
 "tags": [ "cassandra" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "by",
    "label": "Group By",
    "query": "cluster,datacenter,rack,host_name"
   },
   {
    "name": "rate",
    "label": "Rate",
    "query": "1m,5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": "label_values(up{job=\"cassandra-maac\"}, cluster)"
   },
   {
    "name": "datacenter",
    "label": "Datacenter",
    "query": "label_values(up{job=\"cassandra-maac\", cluster=~\"$cluster\"}, datacenter)"
   },
   {
    "name": "rack",
    "label": "Rack",
    "query": "label_values(up{job=\"cassandra-maac\", cluster=~\"$cluster\", datacenter=~\"$datacenter\"}, rack)"
   },
   {
    "name": "keyspace",
    "label": "Keyspace",
    "query": "label_values(org_apache_cassandra_metrics_table_read_latency_count{cluster=~\"$cluster\"}, keyspace)"
   },
   {
    "name": "table",
    "label": "Table",
    "query": "label_values(org_apache_cassandra_metrics_table_read_latency_count{cluster=~\"$cluster\", keyspace=~\"$keyspace\"}, table)"
   },
   {
    "name": "host",
    "label": "Host",
    "query": "label_values(up{job=\"cassandra-maac\", cluster=~\"$cluster\", datacenter=~\"$datacenter\", rack=~\"$rack\"}, host_name)"
   },
   {
    "name": "latency",
    "label": "Percentile",
    "query": "0.999,0.99,0.98,0.95,0.90,0.75,0.50"
   }
  ]
 },
 "panels": [
  { "title": "Cluster Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Nodes Up",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(up{job=\"cassandra-maac\", cluster=~\"$cluster\", datacenter=~\"$datacenter\", rack=~\"$rack\", host_name=~\"$host\"} == 1) or vector(0)"
    }
   ]
  },
  {
   "title": "Nodes Down",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(up{job=\"cassandra-maac\", cluster=~\"$cluster\", datacenter=~\"$datacenter\", rack=~\"$rack\", host_name=~\"$host\"} == 0) or vector(0)"
    }
   ]
  },
  {
   "title": "Compactions / $rate",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(org_apache_cassandra_metrics_compaction_completed_tasks{cluster=~\"$cluster\", datacenter=~\"$datacenter\", rack=~\"$rack\", host_name=~\"$host\"}[$rate]))"
    }
   ]
  },
  {
   "title": "CQL Requests / $rate",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(irate(org_apache_cassandra_metrics_client_request_latency_count{cluster=~\"$cluster\", datacenter=~\"$datacenter\", rack=~\"$rack\", host_name=~\"$host\"}[$rate]))"
    }
   ]
  },
  {
   "title": "Dropped Messages / $rate",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(irate(org_apache_cassandra_metrics_dropped_message_dropped_total{cluster=~\"$cluster\", datacenter=~\"$datacenter\", rack=~\"$rack\", host_name=~\"$host\"}[$rate]))"
    }
   ]
  },
  {
   "title": "CQL Clients",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(org_apache_cassandra_metrics_client_connected_native_clients{cluster=~\"$cluster\", datacenter=~\"$datacenter\", rack=~\"$rack\", host_name=~\"$host\"})"
    }
   ]
  },
  {
   "title": "Timeouts / $rate",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(irate(org_apache_cassandra_metrics_client_request_timeouts_total{cluster=~\"$cluster\", datacenter=~\"$datacenter\", rack=~\"$rack\", host_name=~\"$host\"}[$rate]))"
    }
   ]
  },
  {
   "title": "Hints / $rate",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(irate(org_apache_cassandra_metrics_storage_total_hints{cluster=~\"$cluster\", datacenter=~\"$datacenter\", rack=~\"$rack\", host_name=~\"$host\"}[$rate]))"
    }
   ]
  },
  {
   "title": "Data Size",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(org_apache_cassandra_metrics_table_live_disk_space_used{cluster=~\"$cluster\", datacenter=~\"$datacenter\", rack=~\"$rack\", keyspace=~\"$keyspace\", table=~\"$table\", host_name=~\"$host\"})"
    }
   ]
  },
  {
   "title": "GC Time / $rate",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(jvm_gc_collection_seconds_sum{cluster=~\"$cluster\", datacenter=~\"$datacenter\", rack=~\"$rack\", host_name=~\"$host\"}[$rate]))"
    }
   ]
  },
  { "title": "Request Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Requests Served / $by / $rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(irate({__name__=~\"org_apache_cassandra_metrics_client_request_latency_read_.+_count\", cluster=~\"$cluster\", datacenter=~\"$datacenter\", rack=~\"$rack\", host_name=~\"$host\"}[$rate])) by ($by)",
     "legendFormat": "{{$by}}:read"
    },
    {
     "expr": "sum(irate({__name__=~\"org_apache_cassandra_metrics_client_request_latency_write_.+_count\", cluster=~\"$cluster\", datacenter=~\"$datacenter\", rack=~\"$rack\", host_name=~\"$host\"}[$rate])) by ($by)",
     "legendFormat": "{{$by}}:write"
    },
    {
     "expr": "sum(org_apache_cassandra_metrics_client_connected_native_clients{cluster=~\"$cluster\", datacenter=~\"$datacenter\", rack=~\"$rack\", host_name=~\"$host\"}) by ($by)",
     "legendFormat": "{{$by}}:Clients Connected"
    }
   ]
  },
  {
   "title": "Coordinator $latency Latency / $by",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "histogram_quantile($latency, sum(rate({__name__=~\"org_apache_cassandra_metrics_client_request_latency_read_.+_bucket\", cluster=~\"$cluster\", datacenter=~\"$datacenter\", rack=~\"$rack\", host_name=~\"$host\"}[$rate])) by (le, $by))",
     "legendFormat": "$by:{{$by}} read p{{$latency}}"
    },
    {
     "expr": "histogram_quantile($latency, sum(rate({__name__=~\"org_apache_cassandra_metrics_client_request_latency_write_.+_bucket\", cluster=~\"$cluster\", datacenter=~\"$datacenter\", rack=~\"$rack\", host_name=~\"$host\"}[$rate])) by (le, $by))",
     "legendFormat": "$by:{{$by}} write p{{$latency}}"
    }
   ]
  },
  { "title": "Table Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Memtable Space $keyspace.$table / $by",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(org_apache_cassandra_metrics_table_memtable_off_heap_data_size{cluster=~\"$cluster\", datacenter=~\"$datacenter\", rack=~\"$rack\", keyspace=~\"$keyspace\", table=~\"$table\", host_name=~\"$host\"}) by ($by)",
     "legendFormat": "{{$by}} : Off Heap"
    },
    {
     "expr": "sum(org_apache_cassandra_metrics_table_memtable_on_heap_data_size{cluster=~\"$cluster\", datacenter=~\"$datacenter\", rack=~\"$rack\", keyspace=~\"$keyspace\", table=~\"$table\", host_name=~\"$host\"}) by ($by)",
     "legendFormat": "{{$by}} : On Heap"
    },
    {
     "expr": "sum(idelta(org_apache_cassandra_metrics_table_memtable_switch_count{cluster=~\"$cluster\", datacenter=~\"$datacenter\", rack=~\"$rack\", keyspace=~\"$keyspace\", table=~\"$table\", host_name=~\"$host\"}[$rate])) by ($by)",
     "legendFormat": "{{$by}} : Flushes"
    },
    {
     "expr": "sum(idelta(org_apache_cassandra_metrics_table_pending_flushes{cluster=~\"$cluster\", datacenter=~\"$datacenter\", rack=~\"$rack\", keyspace=~\"$keyspace\", table=~\"$table\", host_name=~\"$host\"}[$rate])) by ($by)",
     "legendFormat": "{{$by}} : Pending Flushes"
    }
   ]
  },
  {
   "title": "Compactions $keyspace.$table / $by",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(irate(org_apache_cassandra_metrics_table_compaction_bytes_written{cluster=~\"$cluster\", datacenter=~\"$datacenter\", rack=~\"$rack\", keyspace=~\"$keyspace\", table=~\"$table\", host_name=~\"$host\"}[$rate])) by ($by)",
     "legendFormat": "{{$by}} : Bytes Compacted"
    },
    {
     "expr": "sum(org_apache_cassandra_metrics_table_pending_compactions{cluster=~\"$cluster\", datacenter=~\"$datacenter\", rack=~\"$rack\", keyspace=~\"$keyspace\", table=~\"$table\", host_name=~\"$host\"}) by ($by)",
     "legendFormat": "{{$by}} : Pending Compactions"
    },
    {
     "expr": "sum(irate(org_apache_cassandra_metrics_compaction_completed_tasks{cluster=~\"$cluster\", datacenter=~\"$datacenter\", rack=~\"$rack\", host_name=~\"$host\"}[$rate])) by ($by)",
     "legendFormat": "{{$by}} : Completed Compactions"
    }
   ]
  },
  {
   "title": "Table $latency Latency / $by",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "histogram_quantile($latency, sum(irate(org_apache_cassandra_metrics_table_range_latency_bucket{cluster=~\"$cluster\", datacenter=~\"$datacenter\", rack=~\"$rack\", keyspace=~\"$keyspace\", table=~\"$table\", host_name=~\"$host\"}[$rate])) by (le, $by))",
     "legendFormat": "$by:{{$by}} Local Range Scan"
    },
    {
     "expr": "histogram_quantile($latency, sum(irate(org_apache_cassandra_metrics_table_read_latency_bucket{cluster=~\"$cluster\", datacenter=~\"$datacenter\", rack=~\"$rack\", keyspace=~\"$keyspace\", table=~\"$table\", host_name=~\"$host\"}[$rate])) by (le, $by))",
     "legendFormat": "$by:{{$by}} Local Read"
    },
    {
     "expr": "histogram_quantile($latency, sum(irate(org_apache_cassandra_metrics_table_write_latency_bucket{cluster=~\"$cluster\", datacenter=~\"$datacenter\", rack=~\"$rack\", keyspace=~\"$keyspace\", table=~\"$table\", host_name=~\"$host\"}[$rate])) by (le, $by))",
     "legendFormat": "$by:{{$by}} Local Write"
    },
    {
     "expr": "histogram_quantile($latency, sum(irate(org_apache_cassandra_metrics_table_coordinator_read_latency_bucket{cluster=~\"$cluster\", datacenter=~\"$datacenter\", rack=~\"$rack\", keyspace=~\"$keyspace\", table=~\"$table\", host_name=~\"$host\"}[$rate])) by (le, $by))",
     "legendFormat": "$by:{{$by}} Coordinator Read"
    },
    {
     "expr": "histogram_quantile($latency, sum(irate(org_apache_cassandra_metrics_table_coordinator_scan_latency_bucket{cluster=~\"$cluster\", datacenter=~\"$datacenter\", rack=~\"$rack\", keyspace=~\"$keyspace\", table=~\"$table\", host_name=~\"$host\"}[$rate])) by (le, $by))",
     "legendFormat": "$by:{{$by}} Coordinator Range Scan"
    }
   ]
  }
 ]
}