{
 "title": "ClickHouse Logs",
 "tags": [
  "logs",
  "clickhouse",
  "otel"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "metrics_datasource", "label": "Metrics", "query": "prometheus" },
   { "name": "logs_datasource", "label": "Logs", "query": "loki" },
   { "name": "traces_datasource", "label": "Traces", "query": "tempo" },
   { "name": "cluster", "label": "Cluster", "query": { "query": "label_values(up, cluster)" } },
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "Recent Errors (Last 5 min)",
   "type": "logs",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{cluster=~\"$cluster\", k8s_container_name=~\".*clickhouse.*\"} | detected_level=\"error\""
    }
   ]
  },
  {
   "title": "Recent Warnings (Last 5 min)",
   "type": "logs",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "{cluster=~\"$cluster\", k8s_container_name=~\".*clickhouse.*\"} | detected_level=\"warn\""
    }
   ]
  },
  {
   "title": "ClickHouse Logs",
   "type": "logs",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "{cluster=~\"$cluster\", k8s_container_name=~\".*clickhouse.*\"}"
    }
   ]
  }
 ]
}