{
 "title": "Cassandra Overview",
 "tags": [
  "cassandra",
  "overview"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": "label_values(up{job=\"cassandra-maac\"}, cluster)"
   },
   {
    "name": "datacenter",
    "label": "Datacenter",
    "query": "label_values(up{job=\"cassandra-maac\", cluster=~\"$cluster\"}, datacenter)"
   },
   {
    "name": "rack",
    "label": "Rack",
    "query": "label_values(up{job=\"cassandra-maac\", cluster=~\"$cluster\", datacenter=~\"$datacenter\"}, rack)"
   },
   {
    "name": "node",
    "label": "Node",
    "query": "label_values(up{job=\"cassandra-maac\", cluster=~\"$cluster\", datacenter=~\"$datacenter\", rack=~\"$rack\"}, host_name)"
   }
  ]
 },
 "panels": [
  {
   "title": "Request Throughputs (Coordinator Perspective)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "Request Throughputs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (cluster) (rate({__name__=~\"org_apache_cassandra_metrics_client_request_latency_read_.+_count\", cluster=~\"$cluster\", datacenter=~\"$datacenter\", rack=~\"$rack\", host_name=~\"$node\"}[1m]))",
     "legendFormat": "read"
    },
    {
     "expr": "sum by (cluster) (rate({__name__=~\"org_apache_cassandra_metrics_client_request_latency_write_.+_count\", cluster=~\"$cluster\", datacenter=~\"$datacenter\", rack=~\"$rack\", host_name=~\"$node\"}[1m]))",
     "legendFormat": "write"
    }
   ]
  },
  {
   "title": "Error Throughputs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (cluster) (rate({__name__=~\"org_apache_cassandra_metrics_client_request_failures_(read|write)_.+_total\", cluster=~\"$cluster\", datacenter=~\"$datacenter\", rack=~\"$rack\", host_name=~\"$node\"}[1m]))",
     "legendFormat": "failures"
    },
    {
     "expr": "sum by (cluster) (rate({__name__=~\"org_apache_cassandra_metrics_client_request_timeouts_(read|write)_.+_total\", cluster=~\"$cluster\", datacenter=~\"$datacenter\", rack=~\"$rack\", host_name=~\"$node\"}[1m]))",
     "legendFormat": "timeouts"
    },
    {
     "expr": "sum by (cluster) (rate({__name__=~\"org_apache_cassandra_metrics_client_request_unavailables_(read|write)_.+_total\", cluster=~\"$cluster\", datacenter=~\"$datacenter\", rack=~\"$rack\", host_name=~\"$node\"}[1m]))",
     "legendFormat": "unavailable"
    }
   ]
  },
  {
   "title": "Read / Write Distribution",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate({__name__=~\"org_apache_cassandra_metrics_client_request_latency_read_.+_count\", cluster=~\"$cluster\", datacenter=~\"$datacenter\", rack=~\"$rack\", host_name=~\"$node\"}[1m])) / (sum(rate({__name__=~\"org_apache_cassandra_metrics_client_request_latency_read_.+_count\", cluster=~\"$cluster\", datacenter=~\"$datacenter\", rack=~\"$rack\", host_name=~\"$node\"}[1m])) + sum(rate({__name__=~\"org_apache_cassandra_metrics_client_request_latency_write_.+_count\", cluster=~\"$cluster\", datacenter=~\"$datacenter\", rack=~\"$rack\", host_name=~\"$node\"}[1m])))",
     "legendFormat": "Reads"
    }
   ]
  },
  {
   "title": "Read Latency (p98 - p999)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 4, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.98, sum(rate({__name__=~\"org_apache_cassandra_metrics_client_request_latency_read_.+_bucket\", cluster=~\"$cluster\", datacenter=~\"$datacenter\", rack=~\"$rack\", host_name=~\"$node\"}[5m])) by (le, cluster))",
     "legendFormat": "p98"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate({__name__=~\"org_apache_cassandra_metrics_client_request_latency_read_.+_bucket\", cluster=~\"$cluster\", datacenter=~\"$datacenter\", rack=~\"$rack\", host_name=~\"$node\"}[5m])) by (le, cluster))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.999, sum(rate({__name__=~\"org_apache_cassandra_metrics_client_request_latency_read_.+_bucket\", cluster=~\"$cluster\", datacenter=~\"$datacenter\", rack=~\"$rack\", host_name=~\"$node\"}[5m])) by (le, cluster))",
     "legendFormat": "p999"
    }
   ]
  },
  {
   "title": "Write Latency (p98 - p999)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.98, sum(rate({__name__=~\"org_apache_cassandra_metrics_client_request_latency_write_.+_bucket\", cluster=~\"$cluster\", datacenter=~\"$datacenter\", rack=~\"$rack\", host_name=~\"$node\"}[5m])) by (le, cluster))",
     "legendFormat": "p98"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate({__name__=~\"org_apache_cassandra_metrics_client_request_latency_write_.+_bucket\", cluster=~\"$cluster\", datacenter=~\"$datacenter\", rack=~\"$rack\", host_name=~\"$node\"}[5m])) by (le, cluster))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.999, sum(rate({__name__=~\"org_apache_cassandra_metrics_client_request_latency_write_.+_bucket\", cluster=~\"$cluster\", datacenter=~\"$datacenter\", rack=~\"$rack\", host_name=~\"$node\"}[5m])) by (le, cluster))",
     "legendFormat": "p999"
    }
   ]
  },
  {
   "title": "All Coordinator Latencies (p99)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(org_apache_cassandra_metrics_client_request_latency_bucket{cluster=~\"$cluster\", datacenter=~\"$datacenter\", rack=~\"$rack\", host_name=~\"$node\"}[1m])) by (le, cluster))",
     "legendFormat": "p99 all operations"
    }
   ]
  },
  { "title": "Nodes Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Nodes Count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(up{job=\"cassandra-maac\", cluster=~\"$cluster\", datacenter=~\"$datacenter\", rack=~\"$rack\", host_name=~\"$node\"})",
     "legendFormat": "Total Nodes"
    }
   ]
  },
  {
   "title": "Nodes Status History",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 18, "x": 6, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "count(up{job=\"cassandra-maac\", cluster=~\"$cluster\", datacenter=~\"$datacenter\", rack=~\"$rack\", host_name=~\"$node\"})",
     "legendFormat": "Total Nodes"
    },
    {
     "expr": "sum by (cluster) (max by (cluster, datacenter, rack, host_name) (changes(org_apache_cassandra_metrics_thread_pools_completed_tasks{cluster=~\"$cluster\", datacenter=~\"$datacenter\", rack=~\"$rack\", host_name=~\"$node\", pool_name=\"native\"}[2m])) > bool 0)",
     "legendFormat": "Nodes Coordinating Requests (Native)"
    },
    {
     "expr": "sum by (cluster) (max by (cluster, datacenter, rack, host_name) (changes(org_apache_cassandra_metrics_thread_pools_completed_tasks{cluster=~\"$cluster\", datacenter=~\"$datacenter\", rack=~\"$rack\", host_name=~\"$node\", pool_name=\"gossip_stage\"}[2m])) > bool 0)",
     "legendFormat": "Nodes With Internal Activity (Gossip)"
    }
   ]
  },
  { "title": "Data Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "Disk Space Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * sum by (host_name, mountpoint) (system_filesystem_usage_bytes{state=\"used\", mountpoint=~\"/mnt/.*|/\", host_name=~\"$node\"}) / (sum by (host_name, mountpoint) (system_filesystem_usage_bytes{state=\"used\", mountpoint=~\"/mnt/.*|/\", host_name=~\"$node\"}) + sum by (host_name, mountpoint) (system_filesystem_usage_bytes{state=\"free\", mountpoint=~\"/mnt/.*|/\", host_name=~\"$node\"}))",
     "legendFormat": "{{host_name}} {{mountpoint}}"
    }
   ]
  },
  {
   "title": "Cassandra Data Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (cluster) (org_apache_cassandra_metrics_table_live_disk_space_used{cluster=~\"$cluster\", datacenter=~\"$datacenter\", rack=~\"$rack\", host_name=~\"$node\"})",
     "legendFormat": "Live space - {{cluster}}"
    },
    {
     "expr": "sum by (cluster) (org_apache_cassandra_metrics_table_total_disk_space_used{cluster=~\"$cluster\", datacenter=~\"$datacenter\", rack=~\"$rack\", host_name=~\"$node\"})",
     "legendFormat": "Total space - {{cluster}}"
    }
   ]
  },
  {
   "title": "SSTable Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max by (cluster, keyspace, table) (org_apache_cassandra_metrics_table_live_ss_table_count{cluster=~\"$cluster\", datacenter=~\"$datacenter\", rack=~\"$rack\", host_name=~\"$node\"})",
     "legendFormat": "{{keyspace}}.{{table}}"
    },
    {
     "expr": "max by (cluster) (org_apache_cassandra_metrics_table_live_ss_table_count{cluster=~\"$cluster\", datacenter=~\"$datacenter\", rack=~\"$rack\", host_name=~\"$node\"})",
     "legendFormat": "Max in cluster"
    }
   ]
  },
  {
   "title": "Pending Compactions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max by (cluster) (org_apache_cassandra_metrics_table_pending_compactions{cluster=~\"$cluster\", datacenter=~\"$datacenter\", rack=~\"$rack\", host_name=~\"$node\"})",
     "legendFormat": "max"
    },
    {
     "expr": "min by (cluster) (org_apache_cassandra_metrics_table_pending_compactions{cluster=~\"$cluster\", datacenter=~\"$datacenter\", rack=~\"$rack\", host_name=~\"$node\"})",
     "legendFormat": "min"
    },
    {
     "expr": "avg by (cluster) (org_apache_cassandra_metrics_table_pending_compactions{cluster=~\"$cluster\", datacenter=~\"$datacenter\", rack=~\"$rack\", host_name=~\"$node\"})",
     "legendFormat": "avg"
    }
   ]
  },
  { "title": "Cassandra Internals", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 } },
  {
   "title": "Pending Tasks",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (cluster, pool_name) (org_apache_cassandra_metrics_thread_pools_pending_tasks{cluster=~\"$cluster\", datacenter=~\"$datacenter\", rack=~\"$rack\", host_name=~\"$node\"})",
     "legendFormat": "{{cluster}} - pending {{pool_name}}"
    }
   ]
  },
  {
   "title": "Blocked Tasks",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (cluster, pool_name) (rate(org_apache_cassandra_metrics_thread_pools_total_blocked_tasks{cluster=~\"$cluster\", datacenter=~\"$datacenter\", rack=~\"$rack\", host_name=~\"$node\"}[1m]))",
     "legendFormat": "{{cluster}} - blocked {{pool_name}}"
    }
   ]
  },
  {
   "title": "Dropped Messages",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (cluster, message_type) (rate(org_apache_cassandra_metrics_dropped_message_dropped_total{cluster=~\"$cluster\", datacenter=~\"$datacenter\", rack=~\"$rack\", host_name=~\"$node\"}[1m]))",
     "legendFormat": "{{cluster}} - dropped {{message_type}}"
    }
   ]
  },
  {
   "title": "Active Tasks",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (cluster, pool_name) (org_apache_cassandra_metrics_thread_pools_active_tasks{cluster=~\"$cluster\", datacenter=~\"$datacenter\", rack=~\"$rack\", host_name=~\"$node\"})",
     "legendFormat": "{{cluster}} - active {{pool_name}}"
    }
   ]
  },
  {
   "title": "Hinted Handoff",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (cluster) (org_apache_cassandra_metrics_storage_total_hints_in_progress{cluster=~\"$cluster\", datacenter=~\"$datacenter\", rack=~\"$rack\", host_name=~\"$node\"})",
     "legendFormat": "Hints in progress"
    }
   ]
  },
  { "title": "Hardware / Operating System", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 68 } },
  {
   "title": "CPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (avg by(host_name) (rate(system_cpu_time_seconds_total{state=\"idle\", host_name=~\"$node\"}[1m])) * 100)",
     "legendFormat": "{{host_name}}"
    }
   ]
  },
  {
   "title": "Unix Load (1m)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "system_cpu_load_average_1m{host_name=~\"$node\"}",
     "legendFormat": "{{host_name}}"
    }
   ]
  },
  {
   "title": "Memory Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "system_memory_usage_bytes{state=\"used\", host_name=~\"$node\"}",
     "legendFormat": "{{host_name}}"
    }
   ]
  },
  {
   "title": "Disk Read Throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 77 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(system_disk_io_bytes_total{direction=\"read\", host_name=~\"$node\"}[1m])",
     "legendFormat": "{{host_name}} read"
    }
   ]
  },
  {
   "title": "Disk Write Throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 77 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(system_disk_io_bytes_total{direction=\"write\", host_name=~\"$node\"}[1m])",
     "legendFormat": "{{host_name}} write"
    }
   ]
  },
  {
   "title": "Network I/O",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 77 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(system_network_io_bytes_total{direction=\"receive\", host_name=~\"$node\"}[1m])",
     "legendFormat": "{{host_name}} rx"
    },
    {
     "expr": "rate(system_network_io_bytes_total{direction=\"transmit\", host_name=~\"$node\"}[1m])",
     "legendFormat": "{{host_name}} tx"
    }
   ]
  },
  { "title": "JVM / Garbage Collection", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 85 } },
  {
   "title": "Application Throughput (% time NOT doing GC)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 86 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "max by (cluster) (1 - sum by (cluster, datacenter, rack, host_name) (rate(jvm_gc_collection_seconds_sum{cluster=~\"$cluster\", datacenter=~\"$datacenter\", rack=~\"$rack\", host_name=~\"$node\"}[1m])))",
     "legendFormat": "max"
    },
    {
     "expr": "min by (cluster) (1 - sum by (cluster, datacenter, rack, host_name) (rate(jvm_gc_collection_seconds_sum{cluster=~\"$cluster\", datacenter=~\"$datacenter\", rack=~\"$rack\", host_name=~\"$node\"}[1m])))",
     "legendFormat": "min"
    },
    {
     "expr": "avg by (cluster) (1 - sum by (cluster, datacenter, rack, host_name) (rate(jvm_gc_collection_seconds_sum{cluster=~\"$cluster\", datacenter=~\"$datacenter\", rack=~\"$rack\", host_name=~\"$node\"}[1m])))",
     "legendFormat": "avg"
    }
   ]
  },
  {
   "title": "Garbage Collection Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 86 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max by (cluster) (rate(jvm_gc_collection_seconds_sum{cluster=~\"$cluster\", datacenter=~\"$datacenter\", rack=~\"$rack\", host_name=~\"$node\"}[1m]))",
     "legendFormat": "max"
    },
    {
     "expr": "min by (cluster) (rate(jvm_gc_collection_seconds_sum{cluster=~\"$cluster\", datacenter=~\"$datacenter\", rack=~\"$rack\", host_name=~\"$node\"}[1m]))",
     "legendFormat": "min"
    },
    {
     "expr": "avg by (cluster) (rate(jvm_gc_collection_seconds_sum{cluster=~\"$cluster\", datacenter=~\"$datacenter\", rack=~\"$rack\", host_name=~\"$node\"}[1m]))",
     "legendFormat": "avg"
    }
   ]
  },
  {
   "title": "JVM Heap Memory Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 86 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max by (cluster) (jvm_memory_bytes_used{area=\"heap\", cluster=~\"$cluster\", datacenter=~\"$datacenter\", rack=~\"$rack\", host_name=~\"$node\"})",
     "legendFormat": "max used"
    },
    {
     "expr": "min by (cluster) (jvm_memory_bytes_used{area=\"heap\", cluster=~\"$cluster\", datacenter=~\"$datacenter\", rack=~\"$rack\", host_name=~\"$node\"})",
     "legendFormat": "min used"
    },
    {
     "expr": "avg by (cluster) (jvm_memory_bytes_used{area=\"heap\", cluster=~\"$cluster\", datacenter=~\"$datacenter\", rack=~\"$rack\", host_name=~\"$node\"})",
     "legendFormat": "avg used"
    },
    {
     "expr": "min by (cluster) (jvm_memory_bytes_max{area=\"heap\", cluster=~\"$cluster\", datacenter=~\"$datacenter\", rack=~\"$rack\", host_name=~\"$node\"})",
     "legendFormat": "Heap available"
    }
   ]
  }
 ]
}