package com.rustyrazorblade.easydblab.events

/**
 * Event listener that renders events to the console (stdout/stderr).
 *
 * Uses [Event.toDisplayString] to produce the exact same output that was previously
 * generated by `outputHandler.handleMessage()`. Error events are written to stderr.
 */
class ConsoleEventListener : EventListener {
    override fun onEvent(envelope: EventEnvelope) {
        val displayString = envelope.event.toDisplayString()
        if (envelope.event.isError()) {
            System.err.println(displayString)
        } else {
            println(displayString)
        }
    }

    override fun close() {
        // No-op for console output
    }
}
