package com.rustyrazorblade.easydblab.events

import kotlinx.serialization.Serializable

/**
 * Root sealed interface for all domain events in the system.
 *
 * Events are pure domain data — they carry no metadata (timestamp, commandName).
 * Metadata is added by [EventBus] when wrapping events in [EventEnvelope].
 *
 * Each concrete event implements [toDisplayString] to produce the exact console output
 * that was previously generated by `outputHandler.handleMessage()`.
 *
 * Event types are organized by domain as sealed sub-interfaces:
 * - Event.Cassandra.* — Cassandra database operations
 * - Event.K3s.* — K3s cluster management
 * - Event.K8s.* — Kubernetes operations
 * - etc.
 *
 * The type discriminator for serialization is derived from the class name.
 */
@Serializable
sealed interface Event {
    /**
     * Returns the human-readable display string for console output.
     * This MUST match the exact string previously passed to `outputHandler.handleMessage()`.
     */
    fun toDisplayString(): String

    /**
     * Whether this event represents an error condition.
     * Error events are written to stderr by ConsoleEventListener.
     */
    fun isError(): Boolean = false

    /** A simple message event for use in tests and as a transitional type during migration. */
    @Serializable
    data class Message(
        val text: String,
    ) : Event {
        override fun toDisplayString(): String = text
    }

    /** A simple error event for use in tests and as a transitional type during migration. */
    @Serializable
    data class Error(
        val text: String,
        val detail: String? = null,
    ) : Event {
        override fun toDisplayString(): String = if (detail != null) "$text\n$detail" else text

        override fun isError(): Boolean = true
    }

    // =========================================================================
    // Event.Cassandra — Cassandra database operations
    // =========================================================================

    @Serializable
    sealed interface Cassandra : Event {
        @Serializable
        data class Starting(
            val host: String,
        ) : Cassandra {
            override fun toDisplayString(): String = "Starting Cassandra on $host..."
        }

        @Serializable
        data class StartedWaitingReady(
            val host: String,
        ) : Cassandra {
            override fun toDisplayString(): String = "Cassandra started, waiting for $host to become UP/NORMAL..."
        }

        @Serializable
        data class Restarting(
            val host: String,
        ) : Cassandra {
            override fun toDisplayString(): String = "Restarting Cassandra on $host..."
        }

        @Serializable
        data class WaitingReady(
            val host: String,
        ) : Cassandra {
            override fun toDisplayString(): String = "Waiting for $host to become UP/NORMAL..."
        }
    }

    // =========================================================================
    // Event.K3s — K3s cluster management
    // =========================================================================

    @Serializable
    sealed interface K3s : Event {
        @Serializable
        data object ClusterStarting : K3s {
            override fun toDisplayString(): String = "Starting K3s cluster..."
        }

        @Serializable
        data class ServerStarting(
            val controlHost: String,
        ) : K3s {
            override fun toDisplayString(): String = "Starting K3s server on control node $controlHost..."
        }

        @Serializable
        data class ServerStartFailed(
            val error: String,
        ) : K3s {
            override fun toDisplayString(): String = "Failed to start K3s server: $error"

            override fun isError(): Boolean = true
        }

        @Serializable
        data class NodeTokenFailed(
            val error: String,
        ) : K3s {
            override fun toDisplayString(): String = "Failed to retrieve K3s node token: $error"

            override fun isError(): Boolean = true
        }

        @Serializable
        data class KubeconfigFailed(
            val error: String,
        ) : K3s {
            override fun toDisplayString(): String = "Failed to download kubeconfig: $error"

            override fun isError(): Boolean = true
        }

        @Serializable
        data class KubeconfigWritten(
            val path: String,
        ) : K3s {
            override fun toDisplayString(): String = "Kubeconfig written to $path"
        }

        @Serializable
        data object KubeconfigInstruction : K3s {
            override fun toDisplayString(): String = "Use 'source env.sh' to configure kubectl for cluster access"
        }

        @Serializable
        data object ClusterStarted : K3s {
            override fun toDisplayString(): String = "K3s cluster started successfully"
        }

        @Serializable
        data class AgentConfiguring(
            val host: String,
            val labels: String,
        ) : K3s {
            override fun toDisplayString(): String = "Configuring K3s agent on $host with labels: $labels..."
        }

        @Serializable
        data class AgentConfigFailed(
            val host: String,
            val error: String,
        ) : K3s {
            override fun toDisplayString(): String = "Failed to configure K3s agent on $host: $error"

            override fun isError(): Boolean = true
        }

        @Serializable
        data class AgentStartFailed(
            val host: String,
            val error: String,
        ) : K3s {
            override fun toDisplayString(): String = "Failed to start K3s agent on $host: $error"

            override fun isError(): Boolean = true
        }
    }

    // =========================================================================
    // Event.K8s — Kubernetes operations
    // =========================================================================

    @Serializable
    sealed interface K8s : Event {
        @Serializable
        data object ManifestsApplying : K8s {
            override fun toDisplayString(): String = "Applying K8s manifests..."
        }

        @Serializable
        data object ManifestsApplied : K8s {
            override fun toDisplayString(): String = "K8s manifests applied successfully"
        }

        @Serializable
        data class ManifestApplied(
            val resourcePath: String,
        ) : K8s {
            override fun toDisplayString(): String = "Manifest applied: $resourcePath"
        }

        @Serializable
        data class NamespaceDeleting(
            val namespace: String,
        ) : K8s {
            override fun toDisplayString(): String = "Deleting $namespace namespace..."
        }

        @Serializable
        data class NamespaceDeleted(
            val namespace: String,
        ) : K8s {
            override fun toDisplayString(): String = "Namespace $namespace deleted"
        }

        @Serializable
        data class PodsWaiting(
            val namespace: String,
        ) : K8s {
            override fun toDisplayString(): String = "Waiting for pods in $namespace to be ready..."
        }

        @Serializable
        data class PodsReady(
            val namespace: String,
        ) : K8s {
            override fun toDisplayString(): String = "All pods in $namespace are ready"
        }

        @Serializable
        data object ObservabilityPodsWaiting : K8s {
            override fun toDisplayString(): String = "Waiting for observability pods to be ready..."
        }

        @Serializable
        data object ObservabilityPodsReady : K8s {
            override fun toDisplayString(): String = "All observability pods are ready"
        }

        @Serializable
        data object ObservabilityNamespaceDeleting : K8s {
            override fun toDisplayString(): String = "Deleting observability namespace..."
        }

        @Serializable
        data object ObservabilityNamespaceDeleted : K8s {
            override fun toDisplayString(): String = "Observability namespace deleted"
        }

        @Serializable
        data class ResourcesDeleting(
            val labelKey: String,
        ) : K8s {
            override fun toDisplayString(): String = "Deleting resources with label $labelKey..."
        }

        @Serializable
        data object ResourcesDeleted : K8s {
            override fun toDisplayString(): String = "Resources deleted successfully"
        }

        @Serializable
        data class ConfigMapCreated(
            val name: String,
        ) : K8s {
            override fun toDisplayString(): String = "Created ConfigMap: $name"
        }

        @Serializable
        data class ConfigMapDeleted(
            val name: String,
        ) : K8s {
            override fun toDisplayString(): String = "Deleted ConfigMap: $name"
        }

        @Serializable
        data object ClickHouseS3ConfigMapCreated : K8s {
            override fun toDisplayString(): String = "Created ClickHouse S3 ConfigMap"
        }

        @Serializable
        data class StatefulSetScaled(
            val name: String,
            val replicas: Int,
        ) : K8s {
            override fun toDisplayString(): String = "Scaled $name to $replicas replicas"
        }

        @Serializable
        data class JobDeleted(
            val jobName: String,
        ) : K8s {
            override fun toDisplayString(): String = "Deleted job: $jobName"
        }

        @Serializable
        data class LocalPvsCreated(
            val count: Int,
            val dbName: String,
        ) : K8s {
            override fun toDisplayString(): String = "Created $count Local PVs for $dbName"
        }

        @Serializable
        data object StorageClassCreated : K8s {
            override fun toDisplayString(): String = "Created local-storage StorageClass"
        }
    }

    // =========================================================================
    // Event.Infra — AWS Infrastructure (VPC, subnet, security group, etc.)
    // =========================================================================

    @Serializable
    sealed interface Infra : Event {
        @Serializable
        data class VpcCreating(
            val name: String,
        ) : Infra {
            override fun toDisplayString(): String = "Creating VPC: $name"
        }

        @Serializable
        data class VpcCreated(
            val vpcId: String,
        ) : Infra {
            override fun toDisplayString(): String = "VPC created: $vpcId"
        }

        @Serializable
        data class VpcUsing(
            val name: String,
        ) : Infra {
            override fun toDisplayString(): String = "Using existing VPC: $name"
        }

        @Serializable
        data class VpcDeleting(
            val vpcId: String,
        ) : Infra {
            override fun toDisplayString(): String = "Deleting VPC: $vpcId"
        }

        @Serializable
        data class VpcDeleted(
            val vpcId: String,
        ) : Infra {
            override fun toDisplayString(): String = "VPC $vpcId deleted successfully"
        }

        @Serializable
        data class SubnetCreating(
            val name: String,
        ) : Infra {
            override fun toDisplayString(): String = "Creating subnet: $name"
        }

        @Serializable
        data class SubnetUsing(
            val name: String,
        ) : Infra {
            override fun toDisplayString(): String = "Using existing subnet: $name"
        }

        @Serializable
        data class InternetGatewayCreating(
            val name: String,
        ) : Infra {
            override fun toDisplayString(): String = "Creating internet gateway: $name"
        }

        @Serializable
        data class InternetGatewayUsing(
            val name: String,
        ) : Infra {
            override fun toDisplayString(): String = "Using existing internet gateway: $name"
        }

        @Serializable
        data object InternetGatewayDetaching : Infra {
            override fun toDisplayString(): String = "Detaching internet gateway..."
        }

        @Serializable
        data class InternetGatewayDeleting(
            val igwId: String,
        ) : Infra {
            override fun toDisplayString(): String = "Deleting internet gateway: $igwId"
        }

        @Serializable
        data class SecurityGroupCreating(
            val name: String,
        ) : Infra {
            override fun toDisplayString(): String = "Creating security group: $name"
        }

        @Serializable
        data class SecurityGroupUsing(
            val name: String,
        ) : Infra {
            override fun toDisplayString(): String = "Using existing security group: $name"
        }

        @Serializable
        data class SecurityGroupRuleConfigured(
            val portDesc: String,
        ) : Infra {
            override fun toDisplayString(): String = "Configured security group ingress rule for $portDesc"
        }

        @Serializable
        data class SecurityGroupRulesRevoking(
            val count: Int,
        ) : Infra {
            override fun toDisplayString(): String = "Revoking rules from $count security groups..."
        }

        @Serializable
        data class SecurityGroupDeleting(
            val sgId: String,
        ) : Infra {
            override fun toDisplayString(): String = "Deleting security group: $sgId"
        }

        @Serializable
        data object RoutingConfigured : Infra {
            override fun toDisplayString(): String = "Configured routing to internet gateway"
        }

        @Serializable
        data class NatGatewayDeleting(
            val natId: String,
        ) : Infra {
            override fun toDisplayString(): String = "Deleting NAT gateway: $natId"
        }

        @Serializable
        data object NatGatewaysWaiting : Infra {
            override fun toDisplayString(): String = "Waiting for NAT gateways to be deleted..."
        }

        @Serializable
        data object NatGatewaysDeleted : Infra {
            override fun toDisplayString(): String = "All NAT gateways deleted"
        }

        @Serializable
        data class RouteTableDeleting(
            val rtId: String,
        ) : Infra {
            override fun toDisplayString(): String = "Deleting route table: $rtId"
        }

        @Serializable
        data class SubnetDeleting(
            val subnetId: String,
        ) : Infra {
            override fun toDisplayString(): String = "Deleting subnet: $subnetId"
        }

        @Serializable
        data class NetworkInterfacesClearing(
            val count: Int,
        ) : Infra {
            override fun toDisplayString(): String = "Waiting for $count network interfaces to clear..."
        }

        @Serializable
        data object NetworkInterfacesCleared : Infra {
            override fun toDisplayString(): String = "All network interfaces cleared"
        }

        @Serializable
        data class InfrastructureEnsuring(
            val vpcName: String,
        ) : Infra {
            override fun toDisplayString(): String = "Ensuring infrastructure exists for: $vpcName"
        }

        @Serializable
        data class InfrastructureReady(
            val vpcName: String,
        ) : Infra {
            override fun toDisplayString(): String = "Infrastructure ready for: $vpcName"
        }

        @Serializable
        data class VpcNetworkingSetup(
            val clusterName: String,
        ) : Infra {
            override fun toDisplayString(): String = "Setting up VPC networking for: $clusterName"
        }

        @Serializable
        data class VpcNetworkingReady(
            val clusterName: String,
        ) : Infra {
            override fun toDisplayString(): String = "VPC networking ready for: $clusterName"
        }

        @Serializable
        data class ResourceDiscovering(
            val vpcId: String,
        ) : Infra {
            override fun toDisplayString(): String = "Discovering resources in VPC: $vpcId"
        }

        @Serializable
        data class VpcTeardownSearching(
            val tagKey: String,
            val tagValue: String,
        ) : Infra {
            override fun toDisplayString(): String = "Finding all VPCs tagged with $tagKey=$tagValue..."
        }

        @Serializable
        data class VpcTeardownNoneFound(
            val tagKey: String,
            val tagValue: String,
        ) : Infra {
            override fun toDisplayString(): String = "No VPCs found with tag $tagKey=$tagValue"
        }

        @Serializable
        data class VpcTeardownFound(
            val count: Int,
        ) : Infra {
            override fun toDisplayString(): String = "Found $count VPCs to tear down"
        }

        @Serializable
        data class PackerVpcSkipping(
            val vpcId: String,
        ) : Infra {
            override fun toDisplayString(): String = "Skipping packer VPC: $vpcId (use --packer to include)"
        }

        @Serializable
        data object PackerVpcSearching : Infra {
            override fun toDisplayString(): String = "Finding packer infrastructure VPC..."
        }

        @Serializable
        data class PackerVpcNotFound(
            val name: String,
        ) : Infra {
            override fun toDisplayString(): String = "No packer VPC found ($name)"
        }
    }

    // =========================================================================
    // Event.Ec2 — EC2 instance operations
    // =========================================================================

    @Serializable
    sealed interface Ec2 : Event {
        @Serializable
        data class InstancesCreating(
            val count: Int,
            val serverType: String,
        ) : Ec2 {
            override fun toDisplayString(): String = "Creating $count $serverType instance(s)..."
        }

        @Serializable
        data class InstancesCreated(
            val count: Int,
            val serverType: String,
        ) : Ec2 {
            override fun toDisplayString(): String = "Created $count $serverType instance(s)"
        }

        @Serializable
        data class InstancesTerminating(
            val count: Int,
        ) : Ec2 {
            override fun toDisplayString(): String = "Terminating $count EC2 instances..."
        }

        @Serializable
        data object InstancesTerminateWaiting : Ec2 {
            override fun toDisplayString(): String = "Waiting for instances to terminate..."
        }

        @Serializable
        data object InstancesTerminated : Ec2 {
            override fun toDisplayString(): String = "All instances terminated"
        }

        @Serializable
        data object InstancesStartWaiting : Ec2 {
            override fun toDisplayString(): String = "Waiting for instances to start..."
        }

        @Serializable
        data object InstancesRunning : Ec2 {
            override fun toDisplayString(): String = "All instances running"
        }

        @Serializable
        data object StatusCheckWaiting : Ec2 {
            override fun toDisplayString(): String = "Waiting for instance status checks to pass..."
        }

        @Serializable
        data object StatusCheckPassed : Ec2 {
            override fun toDisplayString(): String = "Instance status checks passed"
        }

        @Serializable
        data class ExistingInstancesFound(
            val serverType: String,
            val count: Int,
        ) : Ec2 {
            override fun toDisplayString(): String = "Found $count existing $serverType instances, no new instances needed"
        }
    }

    // =========================================================================
    // Event.Emr — EMR & Spark operations
    // =========================================================================

    @Serializable
    sealed interface Emr : Event {
        @Serializable
        data class ClusterCreating(
            val clusterName: String,
        ) : Emr {
            override fun toDisplayString(): String = "Creating EMR cluster: $clusterName..."
        }

        @Serializable
        data class ClusterInitiated(
            val clusterId: String,
        ) : Emr {
            override fun toDisplayString(): String = "EMR cluster initiated: $clusterId"
        }

        @Serializable
        data object ClusterWaiting : Emr {
            override fun toDisplayString(): String = "Waiting for EMR cluster to start..."
        }

        @Serializable
        data object ClusterReady : Emr {
            override fun toDisplayString(): String = "EMR cluster is ready"
        }

        @Serializable
        data class ClusterTerminating(
            val clusterId: String,
        ) : Emr {
            override fun toDisplayString(): String = "Terminating EMR cluster: $clusterId..."
        }

        @Serializable
        data object ClusterTerminateWaiting : Emr {
            override fun toDisplayString(): String = "Waiting for EMR cluster to terminate..."
        }

        @Serializable
        data object ClusterTerminated : Emr {
            override fun toDisplayString(): String = "EMR cluster terminated"
        }

        @Serializable
        data class ClustersTerminating(
            val count: Int,
        ) : Emr {
            override fun toDisplayString(): String = "Terminating $count EMR clusters..."
        }

        @Serializable
        data object ClustersTerminateWaiting : Emr {
            override fun toDisplayString(): String = "Waiting for EMR clusters to terminate..."
        }

        @Serializable
        data object ClustersTerminated : Emr {
            override fun toDisplayString(): String = "All EMR clusters terminated"
        }

        @Serializable
        data object ClusterAlreadyExists : Emr {
            override fun toDisplayString(): String = "EMR cluster already exists, skipping creation"
        }

        @Serializable
        data object SparkJobWaiting : Emr {
            override fun toDisplayString(): String = "Waiting for job completion..."
        }

        @Serializable
        data class SparkJobStateUpdate(
            val state: String,
        ) : Emr {
            override fun toDisplayString(): String = "Job state: $state"
        }

        @Serializable
        data object SparkJobCompleted : Emr {
            override fun toDisplayString(): String = "Job completed successfully"
        }

        @Serializable
        data class SparkStepDetails(
            val details: String,
        ) : Emr {
            override fun toDisplayString(): String = details
        }

        @Serializable
        data class SparkStepError(
            val error: String,
        ) : Emr {
            override fun toDisplayString(): String = error

            override fun isError(): Boolean = true
        }

        @Serializable
        data object SparkLogHeader : Emr {
            override fun toDisplayString(): String = "=== Step Logs ==="
        }

        @Serializable
        data class SparkLogLine(
            val line: String,
        ) : Emr {
            override fun toDisplayString(): String = line
        }

        @Serializable
        data class SparkLogCount(
            val count: Int,
        ) : Emr {
            override fun toDisplayString(): String = "Found $count log entries."
        }

        @Serializable
        data class SparkLogError(
            val error: String,
        ) : Emr {
            override fun toDisplayString(): String = "Could not query logs: $error"

            override fun isError(): Boolean = true
        }

        @Serializable
        data class SparkLogInstruction(
            val stepId: String,
        ) : Emr {
            override fun toDisplayString(): String = "Try: easy-db-lab spark logs --step-id $stepId"
        }

        @Serializable
        data class SparkLogDownloadStart(
            val path: String,
        ) : Emr {
            override fun toDisplayString(): String = "Downloading logs from: $path"
        }

        @Serializable
        data class SparkLogDownloadSaveTo(
            val localPath: String,
        ) : Emr {
            override fun toDisplayString(): String = "Saving to: $localPath"
        }

        @Serializable
        data class SparkLogDownloadComplete(
            val logType: String,
        ) : Emr {
            override fun toDisplayString(): String = "Downloaded: $logType"
        }

        @Serializable
        data class SparkLogDownloadUnavailable(
            val logType: String,
        ) : Emr {
            override fun toDisplayString(): String = "Could not download $logType..."
        }

        @Serializable
        data class SparkLogDownloadFailed(
            val error: String,
        ) : Emr {
            override fun toDisplayString(): String = "Could not download logs: $error"

            override fun isError(): Boolean = true
        }

        @Serializable
        data class SparkDebugInstructions(
            val commands: String,
        ) : Emr {
            override fun toDisplayString(): String = commands
        }

        @Serializable
        data class SparkStderrHeader(
            val lineCount: Int,
        ) : Emr {
            override fun toDisplayString(): String = "=== stderr (last $lineCount lines) ==="
        }

        @Serializable
        data class SparkStderrLine(
            val line: String,
        ) : Emr {
            override fun toDisplayString(): String = line
        }

        @Serializable
        data object SparkStderrFooter : Emr {
            override fun toDisplayString(): String = "=== end stderr ==="
        }

        @Serializable
        data class EmrLogsDownloading(
            val path: String,
        ) : Emr {
            override fun toDisplayString(): String = "Downloading all EMR logs from: $path"
        }

        @Serializable
        data class EmrLogsSaveTo(
            val localDir: String,
        ) : Emr {
            override fun toDisplayString(): String = "Saving to: $localDir"
        }

        @Serializable
        data class StepLogsDownloading(
            val localDir: String,
        ) : Emr {
            override fun toDisplayString(): String = "Downloading step logs to: $localDir"
        }
    }

    // =========================================================================
    // Event.OpenSearch — OpenSearch domain operations
    // =========================================================================

    @Serializable
    sealed interface OpenSearch : Event {
        @Serializable
        data class Creating(
            val domainName: String,
        ) : OpenSearch {
            override fun toDisplayString(): String = "Creating OpenSearch domain: $domainName..."
        }

        @Serializable
        data class Initiated(
            val domainName: String,
        ) : OpenSearch {
            override fun toDisplayString(): String = "OpenSearch domain initiated: $domainName"
        }

        @Serializable
        data object Waiting : OpenSearch {
            override fun toDisplayString(): String = "Waiting for OpenSearch domain to become active..."
        }

        @Serializable
        data object Ready : OpenSearch {
            override fun toDisplayString(): String = "OpenSearch domain is ready"
        }

        @Serializable
        data class WaitProgress(
            val message: String,
            val elapsedMinutes: Long,
        ) : OpenSearch {
            override fun toDisplayString(): String = "$message... ($elapsedMinutes minutes elapsed)"
        }

        @Serializable
        data class Deleting(
            val domainName: String,
        ) : OpenSearch {
            override fun toDisplayString(): String = "Deleting OpenSearch domain: $domainName..."
        }

        @Serializable
        data class DeleteWaiting(
            val domainName: String,
        ) : OpenSearch {
            override fun toDisplayString(): String = "Waiting for OpenSearch domain $domainName to be deleted..."
        }

        @Serializable
        data class Deleted(
            val domainName: String,
        ) : OpenSearch {
            override fun toDisplayString(): String = "OpenSearch domain $domainName deleted"
        }
    }

    // =========================================================================
    // Event.S3 — S3 object store operations
    // =========================================================================

    @Serializable
    sealed interface S3 : Event {
        @Serializable
        data class Uploading(
            val fileName: String,
            val remotePath: String,
        ) : S3 {
            override fun toDisplayString(): String = "Uploading $fileName to $remotePath..."
        }

        @Serializable
        data class UploadComplete(
            val remotePath: String,
        ) : S3 {
            override fun toDisplayString(): String = "Upload complete: $remotePath"
        }

        @Serializable
        data class Downloading(
            val remotePath: String,
            val localPath: String,
        ) : S3 {
            override fun toDisplayString(): String = "Downloading $remotePath to $localPath..."
        }

        @Serializable
        data class DownloadComplete(
            val localPath: String,
        ) : S3 {
            override fun toDisplayString(): String = "Download complete: $localPath"
        }

        @Serializable
        data class Deleting(
            val remotePath: String,
        ) : S3 {
            override fun toDisplayString(): String = "Deleting $remotePath..."
        }

        @Serializable
        data class Deleted(
            val remotePath: String,
        ) : S3 {
            override fun toDisplayString(): String = "Deleted: $remotePath"
        }

        @Serializable
        data class DirectoryDownloadFound(
            val count: Int,
        ) : S3 {
            override fun toDisplayString(): String = "Found $count files to download"
        }

        @Serializable
        data class DirectoryDownloadComplete(
            val count: Int,
            val localDir: String,
        ) : S3 {
            override fun toDisplayString(): String = "Downloaded $count files to $localDir"
        }

        @Serializable
        data class DirectoryUploadFound(
            val count: Int,
            val remotePath: String,
        ) : S3 {
            override fun toDisplayString(): String = "Found $count files to upload to $remotePath"
        }

        @Serializable
        data class DirectoryUploadComplete(
            val count: Int,
            val remotePath: String,
        ) : S3 {
            override fun toDisplayString(): String = "Uploaded $count files to $remotePath"
        }

        @Serializable
        data object NotificationsConfiguring : S3 {
            override fun toDisplayString(): String = "Configuring S3 bucket notifications for EMR logs..."
        }

        @Serializable
        data object NotificationsConfigured : S3 {
            override fun toDisplayString(): String = "S3 bucket notifications configured for EMR logs"
        }

        @Serializable
        data class BucketConfigured(
            val bucket: String,
            val prefix: String,
        ) : S3 {
            override fun toDisplayString(): String = "S3 bucket configured: $bucket (prefix: $prefix)"
        }

        @Serializable
        data class MetricsEnabled(
            val prefix: String,
        ) : S3 {
            override fun toDisplayString(): String = "S3 request metrics enabled for cluster prefix: $prefix"
        }

        @Serializable
        data class BucketUsing(
            val bucket: String,
        ) : S3 {
            override fun toDisplayString(): String = "Using account S3 bucket: $bucket"
        }
    }

    // =========================================================================
    // Event.Sqs — SQS queue operations
    // =========================================================================

    @Serializable
    sealed interface Sqs : Event {
        @Serializable
        data class QueueCreating(
            val queueName: String,
        ) : Sqs {
            override fun toDisplayString(): String = "Creating SQS queue: $queueName"
        }

        @Serializable
        data class QueueCreated(
            val queueUrl: String,
        ) : Sqs {
            override fun toDisplayString(): String = "SQS queue created: $queueUrl"
        }

        @Serializable
        data class QueueDeleting(
            val queueUrl: String,
        ) : Sqs {
            override fun toDisplayString(): String = "Deleting SQS queue: $queueUrl"
        }

        @Serializable
        data object QueueDeleted : Sqs {
            override fun toDisplayString(): String = "SQS queue deleted"
        }

        @Serializable
        data class QueueConfigured(
            val queueUrl: String,
        ) : Sqs {
            override fun toDisplayString(): String = "SQS queue configured for log ingestion: $queueUrl"
        }
    }

    // =========================================================================
    // Event.Grafana — Grafana dashboard operations
    // =========================================================================

    @Serializable
    sealed interface Grafana : Event {
        @Serializable
        data object DatasourcesCreating : Grafana {
            override fun toDisplayString(): String = "Creating Grafana datasources ConfigMap..."
        }

        @Serializable
        data class ResourcesApplying(
            val count: Int,
        ) : Grafana {
            override fun toDisplayString(): String = "Applying $count Grafana resources..."
        }

        @Serializable
        data class ResourceApplying(
            val kind: String,
            val name: String,
        ) : Grafana {
            override fun toDisplayString(): String = "Applying $kind/$name..."
        }

        @Serializable
        data object ResourcesApplied : Grafana {
            override fun toDisplayString(): String = "All Grafana resources applied successfully!"
        }
    }

    // =========================================================================
    // Event.Backup — Backup & restore operations
    // =========================================================================

    @Serializable
    sealed interface Backup : Event {
        @Serializable
        data class VictoriaMetricsStarting(
            val s3Path: String,
        ) : Backup {
            override fun toDisplayString(): String = "Creating VictoriaMetrics backup to $s3Path..."
        }

        @Serializable
        data class VictoriaMetricsJobStarted(
            val jobName: String,
        ) : Backup {
            override fun toDisplayString(): String = "Backup job started: $jobName"
        }

        @Serializable
        data class VictoriaMetricsComplete(
            val s3Path: String,
        ) : Backup {
            override fun toDisplayString(): String = "VictoriaMetrics backup completed: $s3Path"
        }

        @Serializable
        data class VictoriaLogsStarting(
            val s3Path: String,
        ) : Backup {
            override fun toDisplayString(): String = "Creating VictoriaLogs backup to $s3Path..."
        }

        @Serializable
        data class VictoriaLogsJobStarted(
            val jobName: String,
        ) : Backup {
            override fun toDisplayString(): String = "Backup job started: $jobName"
        }

        @Serializable
        data class VictoriaLogsComplete(
            val s3Path: String,
        ) : Backup {
            override fun toDisplayString(): String = "VictoriaLogs backup completed: $s3Path"
        }

        @Serializable
        data object Waiting : Backup {
            override fun toDisplayString(): String = "Waiting for backup to complete..."
        }

        @Serializable
        data class ConfigBackedUp(
            val displayName: String,
            val s3Path: String,
        ) : Backup {
            override fun toDisplayString(): String = "$displayName backed up to S3: $s3Path"
        }

        @Serializable
        data class ConfigRestored(
            val displayName: String,
            val s3Path: String,
        ) : Backup {
            override fun toDisplayString(): String = "$displayName restored from S3: $s3Path"
        }

        @Serializable
        data class KubeconfigBackedUp(
            val s3Path: String,
        ) : Backup {
            override fun toDisplayString(): String = "Kubeconfig backed up to S3: $s3Path"
        }

        @Serializable
        data class KubeconfigRestored(
            val s3Path: String,
        ) : Backup {
            override fun toDisplayString(): String = "Kubeconfig restored from S3: $s3Path"
        }

        @Serializable
        data class K8sManifestsBackedUp(
            val s3Path: String,
        ) : Backup {
            override fun toDisplayString(): String = "K8s manifests backed up to S3: $s3Path"
        }

        @Serializable
        data class K8sManifestsRestored(
            val s3Path: String,
        ) : Backup {
            override fun toDisplayString(): String = "K8s manifests restored from S3: $s3Path"
        }

        @Serializable
        data class CassandraPatchBackedUp(
            val s3Path: String,
        ) : Backup {
            override fun toDisplayString(): String = "Cassandra patch backed up to S3: $s3Path"
        }

        @Serializable
        data class CassandraPatchRestored(
            val s3Path: String,
        ) : Backup {
            override fun toDisplayString(): String = "Cassandra patch restored from S3: $s3Path"
        }

        @Serializable
        data class ClusterLookup(
            val vpcId: String,
        ) : Backup {
            override fun toDisplayString(): String = "Looking up cluster info from VPC: $vpcId"
        }

        @Serializable
        data class ClusterFound(
            val clusterName: String,
            val s3Bucket: String,
        ) : Backup {
            override fun toDisplayString(): String = "Found cluster '$clusterName' with S3 bucket: $s3Bucket"
        }

        @Serializable
        data object RestoreStarting : Backup {
            override fun toDisplayString(): String = "Restoring cluster configuration from S3..."
        }

        @Serializable
        data class RestoreComplete(
            val items: List<String>,
        ) : Backup {
            override fun toDisplayString(): String = "Configuration restored from S3: ${items.joinToString(", ")}"
        }

        @Serializable
        data object RestoreEmpty : Backup {
            override fun toDisplayString(): String = "No configuration files found in S3 to restore"
        }

        @Serializable
        data class StateRestored(
            val clusterName: String,
            val clusterId: String,
            val hostCount: Int,
        ) : Backup {
            override fun toDisplayString(): String = "State restored successfully: cluster=$clusterName, id=$clusterId, hosts=$hostCount"
        }

        @Serializable
        data class IncrementalBackupComplete(
            val filesUploaded: Int,
        ) : Backup {
            override fun toDisplayString(): String = "Backed up $filesUploaded changed configuration files to S3"
        }

        @Serializable
        data class IncrementalBackupFailed(
            val error: String,
        ) : Backup {
            override fun toDisplayString(): String = "Warning: Incremental backup failed: $error"

            override fun isError(): Boolean = true
        }
    }

    // =========================================================================
    // Event.Registry — Container registry operations
    // =========================================================================

    @Serializable
    sealed interface Registry : Event {
        @Serializable
        data class CertGenerating(
            val controlHost: String,
        ) : Registry {
            override fun toDisplayString(): String = "Generating TLS certificate for registry on $controlHost..."
        }

        @Serializable
        data object CertUploaded : Registry {
            override fun toDisplayString(): String = "Uploaded registry certificate to S3"
        }

        @Serializable
        data class TlsConfiguring(
            val host: String,
        ) : Registry {
            override fun toDisplayString(): String = "Configuring registry TLS on $host..."
        }

        @Serializable
        data object TlsConfigured : Registry {
            override fun toDisplayString(): String = "Registry TLS configured on all nodes"
        }
    }

    // =========================================================================
    // Event.Tailscale — Tailscale VPN operations
    // =========================================================================

    @Serializable
    sealed interface Tailscale : Event {
        @Serializable
        data class DaemonStarting(
            val host: String,
        ) : Tailscale {
            override fun toDisplayString(): String = "Starting Tailscale daemon on $host..."
        }

        @Serializable
        data class Authenticating(
            val host: String,
        ) : Tailscale {
            override fun toDisplayString(): String = "Authenticating Tailscale on $host..."
        }

        @Serializable
        data class Connected(
            val host: String,
        ) : Tailscale {
            override fun toDisplayString(): String = "Tailscale connected on $host"
        }

        @Serializable
        data class Stopping(
            val host: String,
        ) : Tailscale {
            override fun toDisplayString(): String = "Stopping Tailscale on $host..."
        }

        @Serializable
        data class Stopped(
            val host: String,
        ) : Tailscale {
            override fun toDisplayString(): String = "Tailscale stopped on $host"
        }
    }

    // =========================================================================
    // Event.AwsSetup — AWS resource setup operations
    // =========================================================================

    @Serializable
    sealed interface AwsSetup : Event {
        @Serializable
        data class Starting(
            val message: String,
        ) : AwsSetup {
            override fun toDisplayString(): String = message
        }

        @Serializable
        data class RepairWarning(
            val errorMessage: String,
        ) : AwsSetup {
            override fun toDisplayString(): String = errorMessage

            override fun isError(): Boolean = true
        }

        @Serializable
        data class CredentialError(
            val error: String,
        ) : AwsSetup {
            override fun toDisplayString(): String = error

            override fun isError(): Boolean = true
        }

        @Serializable
        data class Ec2RoleReady(
            val roleName: String,
        ) : AwsSetup {
            override fun toDisplayString(): String = "EC2 role ready: $roleName"
        }

        @Serializable
        data class EmrServiceRoleReady(
            val roleName: String,
        ) : AwsSetup {
            override fun toDisplayString(): String = "EMR service role ready: $roleName"
        }

        @Serializable
        data class EmrEc2RoleReady(
            val roleName: String,
        ) : AwsSetup {
            override fun toDisplayString(): String = "EMR EC2 role ready: $roleName"
        }

        @Serializable
        data class IamPermissionError(
            val error: String,
        ) : AwsSetup {
            override fun toDisplayString(): String = error

            override fun isError(): Boolean = true
        }

        @Serializable
        data class IamValidationError(
            val error: String,
        ) : AwsSetup {
            override fun toDisplayString(): String = error

            override fun isError(): Boolean = true
        }

        @Serializable
        data class IamUnexpectedError(
            val error: String,
        ) : AwsSetup {
            override fun toDisplayString(): String = error

            override fun isError(): Boolean = true
        }

        @Serializable
        data class ValidationFailed(
            val error: String,
        ) : AwsSetup {
            override fun toDisplayString(): String = error

            override fun isError(): Boolean = true
        }

        @Serializable
        data class Complete(
            val message: String,
        ) : AwsSetup {
            override fun toDisplayString(): String = message
        }
    }

    // =========================================================================
    // Event.Stress — Stress testing operations
    // =========================================================================

    @Serializable
    sealed interface Stress : Event {
        @Serializable
        data class JobStarting(
            val jobName: String,
        ) : Stress {
            override fun toDisplayString(): String = "Starting stress job: $jobName"
        }

        @Serializable
        data class PodStatus(
            val podName: String,
            val status: String,
        ) : Stress {
            override fun toDisplayString(): String = "Pod $podName is $status"
        }
    }

    // =========================================================================
    // Event.Service — SystemD service management
    // =========================================================================

    @Serializable
    sealed interface Service : Event {
        @Serializable
        data class Starting(
            val serviceName: String,
            val host: String,
        ) : Service {
            override fun toDisplayString(): String = "Starting $serviceName on $host..."
        }

        @Serializable
        data class Stopping(
            val serviceName: String,
            val host: String,
        ) : Service {
            override fun toDisplayString(): String = "Stopping $serviceName on $host..."
        }

        @Serializable
        data class Restarting(
            val serviceName: String,
            val host: String,
        ) : Service {
            override fun toDisplayString(): String = "Restarting $serviceName on $host..."
        }
    }

    // =========================================================================
    // Event.Provision — Cluster provisioning operations
    // =========================================================================

    @Serializable
    sealed interface Provision : Event {
        @Serializable
        data object IamUpdating : Provision {
            override fun toDisplayString(): String = "Ensuring IAM policies are up to date..."
        }

        @Serializable
        data object InfrastructureStarting : Provision {
            override fun toDisplayString(): String = "Provisioning infrastructure..."
        }

        @Serializable
        data class EmrReady(
            val masterDns: String,
        ) : Provision {
            override fun toDisplayString(): String = "EMR cluster ready: $masterDns"
        }

        @Serializable
        data class OpenSearchReady(
            val endpoint: String,
        ) : Provision {
            override fun toDisplayString(): String = "OpenSearch domain ready: https://$endpoint"
        }

        @Serializable
        data class OpenSearchDashboards(
            val url: String,
        ) : Provision {
            override fun toDisplayString(): String = url
        }

        @Serializable
        data object InfrastructureFailureHeader : Provision {
            override fun toDisplayString(): String = "\nInfrastructure creation had failures:"

            override fun isError(): Boolean = true
        }

        @Serializable
        data class InfrastructureFailure(
            val resource: String,
            val error: String,
        ) : Provision {
            override fun toDisplayString(): String = "  - $resource: $error"

            override fun isError(): Boolean = true
        }

        @Serializable
        data class ClusterStateUpdated(
            val hostCount: Int,
        ) : Provision {
            override fun toDisplayString(): String = "Cluster state updated: $hostCount hosts tracked"
        }

        @Serializable
        data class InstancesDiscovered(
            val cassandra: Int,
            val stress: Int,
            val control: Int,
        ) : Provision {
            override fun toDisplayString(): String = "Discovered existing instances: Cassandra=$cassandra, Stress=$stress, Control=$control"
        }

        @Serializable
        data class ProvisioningComplete(
            val message: String,
        ) : Provision {
            override fun toDisplayString(): String = message
        }

        @Serializable
        data class ProvisioningInstructions(
            val message: String,
        ) : Provision {
            override fun toDisplayString(): String = message
        }

        @Serializable
        data object SshWaiting : Provision {
            override fun toDisplayString(): String = "Waiting for SSH to come up.."
        }

        @Serializable
        data class SshRetrying(
            val attempt: Int,
        ) : Provision {
            override fun toDisplayString(): String = "SSH still not up yet, waiting... (attempt $attempt)"
        }

        @Serializable
        data class NodeSetupInstructions(
            val message: String,
        ) : Provision {
            override fun toDisplayString(): String = message
        }

        @Serializable
        data class AxonOpsSetup(
            val org: String,
        ) : Provision {
            override fun toDisplayString(): String = "Setting up axonops for $org"
        }

        @Serializable
        data object TailscaleStarting : Provision {
            override fun toDisplayString(): String = "Starting Tailscale VPN..."
        }

        @Serializable
        data class TailscaleWarning(
            val error: String,
        ) : Provision {
            override fun toDisplayString(): String = "Warning: Failed to start Tailscale: $error"

            override fun isError(): Boolean = true
        }

        @Serializable
        data object TailscaleManualInstruction : Provision {
            override fun toDisplayString(): String = "You can manually start it later with: easy-db-lab tailscale start"
        }

        @Serializable
        data object NoControlNodes : Provision {
            override fun toDisplayString(): String = "No control nodes found, skipping K3s setup"

            override fun isError(): Boolean = true
        }

        @Serializable
        data class NodeLabeling(
            val count: Int,
        ) : Provision {
            override fun toDisplayString(): String = "Labeling $count db nodes with ordinals..."
        }

        @Serializable
        data object NodeLabelingComplete : Provision {
            override fun toDisplayString(): String = "Node labeling complete"
        }

        @Serializable
        data object LogPipelineValidating : Provision {
            override fun toDisplayString(): String = "Validating log ingestion pipeline..."
        }

        @Serializable
        data object LogPipelineValid : Provision {
            override fun toDisplayString(): String = "✓ S3 → SQS notifications configured correctly"
        }

        @Serializable
        data class VpcCreating(
            val clusterName: String,
        ) : Provision {
            override fun toDisplayString(): String = "Creating VPC for cluster: $clusterName"
        }

        @Serializable
        data class VpcCreated(
            val vpcId: String,
        ) : Provision {
            override fun toDisplayString(): String = "VPC created: $vpcId"
        }

        @Serializable
        data object OpenSearchCreating : Provision {
            override fun toDisplayString(): String = "Creating OpenSearch domain..."
        }

        @Serializable
        data class AxonOpsConfigWritten(
            val configFile: String,
        ) : Provision {
            override fun toDisplayString(): String = "AxonOps configuration written to $configFile"
        }
    }

    // =========================================================================
    // Event.Command — Command execution & errors
    // =========================================================================

    @Serializable
    sealed interface Command : Event {
        @Serializable
        data class ExecutionError(
            val error: String,
        ) : Command {
            override fun toDisplayString(): String = error

            override fun isError(): Boolean = true
        }

        @Serializable
        data object RetryInstruction : Command {
            override fun toDisplayString(): String = "\nYou can now run the command again."
        }

        @Serializable
        data object DockerNotAvailable : Command {
            override fun toDisplayString(): String = "Error: Docker is not available or not running."

            override fun isError(): Boolean = true
        }

        @Serializable
        data class DockerSetupInstruction(
            val instruction: String,
        ) : Command {
            override fun toDisplayString(): String = instruction

            override fun isError(): Boolean = true
        }

        @Serializable
        data class SshKeyMissing(
            val path: String,
        ) : Command {
            override fun toDisplayString(): String = "SSH key not found at $path"

            override fun isError(): Boolean = true
        }
    }
}
