{
 "title": "ClickHouse Logs",
 "tags": [
  "logs",
  "clickhouse",
  "otel"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "Recent Errors (Last 5 min)",
   "type": "logs",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "_time:5m database:clickhouse level:Error"
    }
   ]
  },
  {
   "title": "Recent Warnings (Last 5 min)",
   "type": "logs",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "_time:5m database:clickhouse level:Warning"
    }
   ]
  },
  {
   "title": "ClickHouse Logs",
   "type": "logs",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 8 },
   "targets": [
    { "expr": "database:clickhouse" }
   ]
  }
 ]
}